repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --files, 'backend/']
    # Run the formatter.
    - id: ruff-format
      args: [--files, 'backend/']