services:
  frontend:
    build:
      context: .
      dockerfile: compose/frontend/Dockerfile  # Make sure to use the correct Dockerfile path
    ports:
      - "80:80"  # Expose nginx port to serve the app
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./.env:/app/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
